import { Product } from "./types/product";

export const sampleProducts: Product[] = [
  {
    name: "Nike Slim tshirt",
    slug: "nike-slim-tshirt",
    category: "pants",
    image: "../public/images/p1.jpg",
    price: 220,
    brand: "Lactose",
    countInStock: 20,
    description: "good tshirt",
    rating: 4.7,
    numReviews: 19,
  },
  {
    name: "Nike Slim socks",
    slug: "nike-slim-socks",
    category: "socks",
    image: "../public/images/p3.jpg",
    price: 100,
    brand: "Lactose",
    countInStock: 15,
    description: "good socks",
    rating: 0.7,
    numReviews: 119,
  },
  {
    name: "Nike Slim shorts",
    slug: "nike-slim-shorts",
    category: "pants",
    image: "../public/images/p2.jpg",
    price: 300,
    brand: "Lactose",
    countInStock: 25,
    description: "good shorts",
    rating: 3.7,
    numReviews: 24,
  },
];
